### ISSUE TITLE
PHP Parse error:  Unclosed '{' on line 143 does not match ')' in template_api.php on line 184

### ISSUE THREAD

**Issue by pkbarbiedoll** [mantisbt-plugins/mailtemplate#2]
The following line (row 184) of the updated template_api.php file has a syntax error:

	$row_1 = db_fetch_array($t_result))

The line should be:

	$row_1 = db_fetch_array($t_result);

**Comment by pkbarbiedoll** [comment]
I am going to attempt to do a pull request to fix this - this will be my first time, so please bear wtih.

**Comment by ghost** [comment]
Pretty close but not correct, line should be:
$row_1 = db_fetch_array($t_result));
Have fixed thios one also
