### ISSUE TITLE
Unknown column 'C.id' in 'where clause' on template_api.php

### ISSUE THREAD

**Issue by pkbarbiedoll** [mantisbt-plugins/mailtemplate#3]
This happens when a notificaiton email is attempted: 

APPLICATION ERROR #401

Database query failed. Error received from database was #1054: Unknown column 'C.id' in 'where clause' for the query: SELECT summary,name FROM mantis_bug_table B , mantis_category_table WHERE B.category_id = C.id and B.id = 1977.
Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.

I will fix it in addition to the other issue.

**Comment by ghost** [comment]
Both errors have been fixed now
