### ISSUE TITLE
Modificación template_api.php

### ISSUE THREAD

**Issue by silasalle** [mantisbt-plugins/mailtemplate#6]
Hola

Falta añadir $cfdata .='< / table >'; en template_api.php para que incorpore la tabla de campos personalizados el final de esta consulta:

		$cfdata = '<table><tr><b><td width="40%">Field</td><td width="60%">Value</td></b></tr>';
		foreach( $issue_data['custom_fields'] as $t_custom_field_name => $t_custom_field_data ) {
			$cfdata .= '<tr><td>'.utf8_str_pad( lang_get_defaulted( $t_custom_field_name, null ) . ': ', $t_email_padding_length, ' ', STR_PAD_RIGHT ).'</td>';
			$cfdata .= '<td>'.string_custom_field_value_for_email( $t_custom_field_data['value'], $t_custom_field_data['type'] ).'</td></tr>';
		}
		$cfdata .='</table>';

	} else {
		$cfdata = "Not Available";
	}

**Comment by ghost** [comment]
Hi Silasalle, what is the change opposite the current code?

**Comment by silasalle** [comment]
Buenos días

Su código original aparece de la siguiente forma y da problemas con el resto de tablas que se incorporan posterior a campos personalizados:

$custom_fields = $issue_data['custom_fields'];
	if (!empty($custom_fields)) {
		$cfdata = '<table><tr><b><td width="40%">Field</td><td width="60%">Value</td></b></tr>';
		foreach( $issue_data['custom_fields'] as $t_custom_field_name => $t_custom_field_data ) {
			$cfdata .= '<tr><td>'.utf8_str_pad( lang_get_defaulted( $t_custom_field_name, null ) . ': ', $t_email_padding_length, ' ', STR_PAD_RIGHT ).'</td>';
			$cfdata .= '<td>'.string_custom_field_value_for_email( $t_custom_field_data['value'], $t_custom_field_data['type'] ).'</td></tr>';
		}
	} else {
		$cfdata = "Not Available";
	}
	$variables['cfdata'] = $cfdata ;

Este es el código que yo he incorporado para que no haya problemas:

i	$custom_fields = $issue_data['custom_fields'];
	if (!empty($custom_fields)) {
		$cfdata = '<table><tr><b><td width="40%">Field</td><td width="60%">Value</td></b></tr>';
		foreach( $issue_data['custom_fields'] as $t_custom_field_name => $t_custom_field_data ) {
			$cfdata .= '<tr><td>'.utf8_str_pad( lang_get_defaulted( $t_custom_field_name, null ) . ': ', $t_email_padding_length, ' ', STR_PAD_RIGHT ).'</td>';
			$cfdata .= '<td>'.string_custom_field_value_for_email( $t_custom_field_data['value'], $t_custom_field_data['type'] ).'</td></tr>';
		}
		$cfdata .='</table>';

	} else {
		$cfdata = "Not Available";
	}
	$variables['cfdata'] = $cfdata ;

Adjunto el fichero original y el modificado.

[template_api.zip](https://github.com/user-attachments/files/17699428/template_api.zip)

**Comment by ghost** [comment]
Gracias Silasalle, I have applied the change to my file.
